### ISSUE TITLE
Annotation won't appear

### ISSUE THREAD

**Issue by felixsdgh** [sywhb/logseq-omnivore#1]
First of all, thanks so much for that plugin! One little hint: I just realized, that the plugin syncs well the highlights made in Omnivore. Even if I add more highlights later on, they will appear in Logseq. Somehow the annotations made with the highlights won't.

**Comment by sywhb** [comment]
Hey @felixsdgh thanks so much for the report. I have created a new repo for this plugin here: https://github.com/omnivore-app/logseq-omnivore 

I'm working on adding the annotations while I will move this issue over there

**Comment by sywhb** [comment]
Hey @felixsdgh I added annotation in v1.4.4
